#!/usr/bin/env bash
# Bash (init) script that manages "manage_my_process"

PID_FILE=/var/run/my_process.pid

start() {
    ./manage_my_process &
    echo "$!" > "$PID_FILE"
}

stop() {
    sudo kill -15 "$(cat "$PID_FILE")" && rm -f "$PID_FILE"
}

case "$1" in 
    start)
       start
       echo "manage_my_process started"
       ;;
    stop)
       stop
       echo "manage_my_process stopped"
       ;;
    restart)
       stop
       start
       echo "manage_my_process restarted"
       ;;
    *)
       echo "Usage: manage_my_process {start|stop|restart}"
esac

exit 0
