#!/usr/bin/env bash
# Bash script that displays specific information from /etc/passwd.
# Displays username, user id, and home directory path for each user.
passwd="/etc/passwd"
while read -r passwd; do
  echo "$passwd" | cut -d ':' --fields=1,3,6
done
