#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterationsi=1
i=1
while [ "$i" -le 20 ]; do
	case $i in
		4)
			echo -e "$i\nbad luck from China"
			;;
		9)
			echo -e "$i\nbad luck from Japan"
			;;
		17)
			echo -e "$i\nbad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac
	((i++))
done
